export const DEFAULT_COMPOSITION_PROMPTS: { [group: string]: string[] } = {
  'View Angle': [
    'dutch angle',
    'from above',
    'from behind',
    'from below',
    'from side',
    'sideways',
    'straight-on',
    'upside-down'
  ],
  'Perspective / Depth': ['atmospheric perspective', 'fisheye', 'panorama', 'perspective', 'vanishing point'],
  Composition: [
    'afterimage',
    'outside border',
    'fading border',
    'rounded corners',
    'viewfinder',
    'chart',
    'bust chart',
    'character chart',
    'reference sheet',
    'diagram',
    'move chart',
    'relationship graph',
    'seating chart',
    'stats',
    'collage',
    'column lineup',
    'out of frame',
    'fake scrollbar',
    'head out of frame',
    'out-of-frame censoring',
    'outside border',
    'from outside',
    'glitch',
    'isometric',
    'letterboxed',
    'lineup',
    'mosaic art',
    'photomosaic',
    'negative space',
    'omake',
    'partially underwater shot',
    'pov',
    'social media composition',
    'symmetry',
    'polar opposites',
    'rotational symmetry',
    'trim marks'
  ],
  'Subject matter': [
    'cityscape',
    'landscape',
    'nature',
    'everyone',
    'absolutely everyone',
    'no humans',
    'off-topic',
    'scenery',
    'still life',
    'animal focus',
    'armpit focus',
    'ass focus',
    'back focus',
    'book focus',
    'breast focus',
    'cloud focus',
    'eye focus',
    'food focus',
    'foot focus',
    'hand focus',
    'hip focus',
    'male focus',
    'navel focus',
    'other focus',
    'pectoral focus',
    'solo focus',
    'vehicle focus',
    'text focus',
    'thigh focus',
    'weapon focus',
    'vehicle focus',
    'wind chime focus'
  ],
  'Locations - Indoors': [
    'bathroom',
    'bathtub',
    'toilet stall',
    'shower',
    'bedroom',
    'hotel room',
    'messy room',
    'otaku room',
    'cafeteria',
    'changing room',
    'classroom',
    'clubroom',
    'conservatory',
    'courtroom',
    'dining room',
    'dressing room',
    'dungeon',
    'prison cell',
    'fitting room',
    'gym',
    'locker room',
    'gym storeroom',
    'infirmary',
    'kitchen',
    'laboratory',
    'library',
    'living room',
    'office',
    'cubicle',
    'pool',
    'stage',
    'staff room',
    'storage room',
    'armory',
    'closet',
    'workshop'
  ],
  'Locations - Outdoors': [
    'beach',
    'shore',
    'canyon',
    'cave',
    'cliff',
    'desert',
    'oasis',
    'forest',
    'bamboo forest',
    'glacier',
    'hill',
    'island',
    'floating island',
    'jungle',
    'meadow',
    'mountain',
    'volcano',
    'nature',
    'park',
    'playground',
    'parking lot',
    'plain',
    'savannah',
    'wetland',
    'water',
    'geyser',
    'lake',
    'ocean',
    'seafloor',
    'pond',
    'river',
    'stream',
    'waterfall',
    'wasteland'
  ],
  'Locations - Man-made': [
    'airfield',
    'runway',
    'amusement park',
    'carousel',
    'ferris wheel',
    'roller coaster',
    'aqueduct',
    'bridge',
    'rope bridge',
    'wooden bridge',
    'canal',
    'city',
    'floating city',
    'rural',
    'town',
    'village',
    'dam',
    'dock',
    'drydock',
    'shipyard',
    'garden',
    'graveyard',
    'jetty',
    'field',
    'flower field',
    'rice paddy',
    'wheat field',
    'fountain',
    'harbor',
    'market',
    'market stall',
    'pier',
    'phone booth',
    'pool',
    'poolside',
    'waterpark',
    'railroad tracks',
    'railroad crossing',
    'road',
    'alley',
    'crosswalk',
    'dirt road',
    'highway',
    'path',
    'sidewalk',
    'stone walkway',
    'street',
    'soccer field',
    'running track',
    'trench',
    'tunnel',
    'well',
    'zoo'
  ],
  'Locations - Buildings': [
    'airport',
    'control tower',
    'hangar',
    'runway',
    'apartment',
    'aquarium',
    'arcade',
    'bar',
    'izakaya',
    'tavern',
    'barn',
    'bunker',
    'bus stop',
    'bowling alley',
    'cafe',
    'casino',
    'castle',
    'floating castle',
    'church',
    'construction site',
    'convention',
    'garage',
    'gas station',
    'gazebo',
    'greenhouse',
    'gym',
    'hospital',
    'house',
    'hotel',
    'hut',
    'industrial',
    'factory',
    'refinery',
    'powerplant',
    'nuclear powerplant',
    'cooling tower',
    'warehouse',
    'library',
    'lighthouse',
    'mall',
    'megastructure',
    'space elevator',
    'military base',
    'mosque',
    'museum',
    'art gallery',
    'nightclub',
    'observatory',
    'office',
    'onsen',
    'pagoda',
    'planetarium',
    'prison',
    'restaurant',
    'rooftop',
    'ruins',
    'school',
    'skating rink',
    'shack',
    'shrine',
    'shop',
    'bakery',
    'bookstore',
    'convenience store',
    'flower shop',
    'pharmacy',
    'salon',
    'sex shop',
    'supermarket',
    'weapon shop',
    'skyscraper',
    'stadium',
    'arena',
    'stilt house',
    'temple',
    'theater',
    'amphitheater',
    'movie theater',
    'tower',
    'bell tower',
    'clock tower',
    'guard tower',
    'minaret',
    'train station',
    'treehouse',
    'windmill'
  ],
  'Locations - Other': [
    'chireiden',
    'eientei',
    'forest of magic',
    'former capital',
    'garden of the sun',
    'hakugyokurou',
    'hakurei shrine',
    'hokkai',
    'kourindou',
    'makai',
    'misty lake',
    'moriya shrine',
    'myouren temple',
    'nameless hill',
    'palanquin ship',
    'scarlet devil mansion',
    'shining needle castle',
    'voile',
    'youkai mountain',
    'divine spirit mausoleum',
    'space',
    'asteroid',
    'moon',
    'planet',
    'space station',
    'vehicle interior',
    'airplane interior',
    'bus interior',
    'car interior',
    'cockpit',
    'spacecraft interior',
    'tank interior',
    'train interior'
  ],
  Framing: [
    'face',
    'portrait',
    'upper body',
    'lower body',
    'cowboy shot',
    'feet out of frame',
    'full body',
    'wide shot',
    'very wide shot',
    'close-up',
    'cut-in',
    'split crop',
    'cropped legs',
    'cropped torso',
    'cropped arms',
    'cropped shoulders',
    'cropped head'
  ],
  Styles: [
    'abstract',
    'art deco',
    'art nouveau',
    'fine art parody',
    'flame painter',
    'impressionism',
    'ligne claire',
    'nihonga',
    'minimalism',
    'realistic',
    'photorealistic',
    'sketch',
    'surreal',
    'unfinished'
  ],
  Techniques: [
    'backlighting',
    'blending',
    'bloom',
    'bokeh',
    'caustics',
    'chiaroscuro',
    'chromatic aberration',
    'diffraction spikes',
    'depth of field',
    'dithering',
    'drop shadow',
    'emphasis lines',
    'film grain',
    'foreshortening',
    'gradient',
    'halftone',
    'double exposure',
    'lens flare',
    'motion blur',
    'motion lines',
    'multiple monochrome',
    'optical illusion',
    'scanlines',
    'silhouette',
    'speed lines',
    'vignetting'
  ],
  Flaws: [
    'Artifacts',
    'gif artifacts',
    'jpeg artifacts',
    'aliasing',
    'vhs artifacts',
    'bad aspect ratio',
    'blurry',
    'censored',
    'uncensored',
    'duplicate',
    'bad reflection',
    'extra digits',
    'typo',
    'lossless-lossy',
    'lossy-lossless',
    'image macro',
    'md5 mismatch',
    'moire',
    'poorly drawn',
    'anatomical nonsense',
    'bad anatomy',
    'bad feet',
    'bad hands',
    'bad proportions',
    'ranguage',
    'reversed',
    'rotated',
    'solid color thumbnail',
    'unmoving pattern',
    'watermark',
    'extraction'
  ]
};
