export const DEFAULT_EXPRESSION_PROMPTS: { [group: string]: string[] } = {
  Misc: [
    'blinking',
    'closed eyes',
    'wince',
    'one eye closed',
    'eye contact',
    'looking afar',
    'looking at ...',
    'looking away',
    'looking back',
    'looking down',
    'looking outside',
    'looking over eyewear',
    'looking through legs',
    'looking to the side',
    'looking up',
    'cross-eyed',
    'googly eyes',
    'half-closed eyes',
    'lazy eye',
    'rolling eyes',
    'shading eyes',
    'squinting',
    'staring',
    'uneven eyes',
    'upturned eyes',
    'wall-eyed',
    'wide-eyed',
    'breast awe',
    'food awe',
    'muscle awe',
    'penis awe',
    'staring',
    'foodgasm',
    'chestnut mouth',
    'constricted pupils',
    'cross-eyed',
    'dot mouth',
    'mouth drool',
    'no mouth',
    'rectangular mouth',
    'sideways mouth',
    'split mouth',
    'wavy mouth',
    'wide-eyed'
  ],
  Lips: ['Licking lips', 'Biting own lip', 'Open mouth', 'Parted lips', 'Puckered lips', 'Pursed lips', 'Pouty lips'],
  Emotions: [
    'angry',
    'anger vein',
    'annoyed',
    'clenched teeth',
    'scowl',
    'annoyed',
    'blush',
    'blush stickers',
    'embarrassed',
    'full-face blush',
    'nose blush',
    'bored',
    'closed eyes',
    'confused',
    'crazy',
    'despair',
    'determined',
    'disappointed',
    'disdain',
    'disgust',
    'drunk',
    'envy',
    'evil',
    'excited',
    'exhausted',
    'expressionless',
    'facepalm',
    'flustered',
    'frustrated',
    'furrowed brow',
    'grimace',
    'guilt',
    'happy',
    'kubrick stare',
    'lonely',
    'nervous',
    'nosebleed',
    'winking',
    'open mouth',
    'parted lips',
    'pain',
    'pout',
    'raised eyebrow',
    'rape face',
    'rolling eyes',
    'sad',
    'depressed',
    'frown',
    'gloom (expression)',
    'tears',
    'scared',
    'panicking',
    'worried',
    'serious',
    'sigh',
    'sleepy',
    'sulking',
    'surprised',
    'thinking',
    'pensive',
    'v-shaped eyebrows',
    'wince'
  ],
  Sexual: [
    'afterglow',
    'ahegao',
    'torogao',
    'sexual ecstasy',
    'fucked silly',
    'aroused',
    'in heat',
    'naughty face',
    'seductive smile'
  ],
  Smiles: [
    'crazy smile',
    'evil smile',
    'fingersmile',
    'forced smile',
    'glasgow smile',
    'grin',
    'evil grin',
    'light smile',
    'sad smile',
    'seductive smile',
    'stifled laugh'
  ],
  Smug: ['doyagao', 'self-satisfied', 'smirk', 'smug', 'troll face'],
  'Sad / Scared / Surprised': [
    'color drain',
    'depressed',
    'despair',
    'gloomy',
    'horrified',
    'screaming',
    'sobbing',
    'traumatized',
    'turn pale',
    'wavy mouth',
    'upset'
  ]
};
