export const DEFAULT_BODY_PROMPTS: { [group: string]: string[] } = {
  Types: ['giant', 'giantess', 'miniboy', 'minigirl', 'muscular', 'muscular female', 'plump', 'curvy', 'fat', 'skinny'],
  Chest: [
    'flat chest',
    'small breasts',
    'medium breasts',
    'large breasts',
    'huge breasts',
    'gigantic breasts',
    'asymmetrical breasts',
    'bouncing breasts',
    'breasts apart',
    'floating breasts',
    'hanging breasts',
    'perky breasts',
    'sagging breasts',
    'unaligned breasts',
    'veiny breasts',
    'pointy breasts',
    'dark nipples',
    'covered nipples',
    'huge nipples',
    'inverted nipples',
    'long nipples',
    'nipple slip',
    'no nipples',
    'puffy nipples',
    'small nipples',
    'areola slip',
    'dark areolae',
    'glands of montgomery',
    'large areolae',
    'light areolae',
    'areola piercing',
    'nipple piercing',
    'nipple bar',
    'nipple bells',
    'nipple chain',
    'nipple clamps',
    'nipple leash',
    'nipple rings',
    'nipple tag',
    'nipple tassels',
    'large pectorals',
    'huge pectorals',
    'manboobs',
    'Broad shoulders',
    'Nape',
    'Shoulder blades'
  ],
  Waist: [
    'abs',
    'belly',
    'midriff',
    'navel',
    'obliques',
    'narrow waist',
    'wide hips',
    'love handles',
    'dimples of venus',
    'cameltoe',
    'flat ass',
    'huge ass',
    'round ass',
    'anal hair',
    'anus',
    'no anus',
    'spread anus',
    'tiny anus'
  ],
  'Female Genitals': [
    'Clitoris',
    'Clitoris piercing',
    'Clitoris ring',
    'Erect clitoris',
    'Cleft of venus',
    'Labia',
    'Fat mons',
    'Dark labia',
    'Long labia',
    'Pubic hair',
    'Pussy',
    'No pussy',
    'pubic hair',
    'futanari'
  ],
  'Male Genitals': [
    'animal penis',
    'dog penis',
    'dolphin penis',
    'horse penis',
    'pig penis',
    'dark penis',
    'erection',
    'flaccid',
    'half-erect',
    'girthy penis',
    'glowing penis',
    'knotted penis',
    'mole on penis',
    'penis piercing',
    'penis tentacle',
    'small penis',
    'large penis',
    'huge penis',
    'gigantic penis',
    'spiked penis',
    'veiny penis',
    'multiple penises',
    'extra penises',
    'pseudopenis',
    'foreskin',
    'phimosis',
    'small testicles',
    'large testicles',
    'huge testicles',
    'gigantic testicles',
    'sagging testicles',
    'veiny testicles'
  ],
  Wings: [
    'Large wings',
    'Mini wings',
    'Angel wings',
    'Demon wings',
    'Dragon wings',
    'Fairy wings',
    'Insect wings',
    'Butterfly wings',
    'Dragonfly wings',
    'Ladybug wings',
    'Moth wings',
    'Bat wings',
    'Crystal wings',
    'Energy wings',
    'Fiery wings',
    'Ice wings',
    'Light hawk wings',
    'Liquid wings',
    'Artificial wings',
    'Fake wings',
    'Hair wings',
    'Mechanical wings',
    'Metal wings',
    'Plant wings',
    'Feathered wings',
    'Black wings',
    'Gradient wings',
    'Red wings',
    'White wings',
    'Blue wings',
    'Green wings',
    'Brown wings',
    'Transparent wings',
    'Yellow wings',
    'Pink wings',
    'Rainbow wings',
    'Grey wings',
    'Ankle wings',
    'Detached wings',
    'Head wings',
    'Low wings',
    'Leg wings',
    'Wrist wings',
    'Wing ears',
    'Winged arms'
  ],
  Tails: [
    'Demon tail',
    'Dragon tail',
    'Ghost tail',
    'Pikachu tail',
    'Snake head tail',
    'Fiery tail',
    'Bear tail',
    'Rabbit tail',
    'Cat tail',
    'Cow tail',
    'Deer tail',
    'Dog tail',
    'Ermine tail',
    'Fox tail',
    'Horse tail',
    'Leopard tail',
    'Lion tail',
    'Monkey tail',
    'Mouse tail',
    'Pig tail',
    'Sheep tail',
    'Squirrel tail',
    'Tiger tail',
    'Wolf tail',
    'Crocodilian tail',
    'Fish tail',
    'Scorpion tail',
    'Snake tail',
    'Tadpole tail'
  ],
  Injuries: [
    'blood',
    'bleeding',
    'blood on bandages',
    'bruise',
    'bruised eye',
    'cuts',
    'deep wound',
    'head bump',
    'missing eye',
    'nosebleed',
    'scar',
    'scratches',
    'stitches',
    'scrape',
    'sprain',
    'stab',
    'impaled',
    'severed limb',
    'amputee',
    'track marks',
    'paralysis',
    'bandaid',
    'bandaid on knee',
    'bandaid on arm',
    'bandaid on leg',
    'bandaid on face',
    'bandaid on cheek',
    'bandaid on ear',
    'bandaid on forehead',
    'bandaid on nose',
    'bandages',
    'bandage on face',
    'bandage over one eye',
    'eyepatch',
    'sarashi',
    'sling (medical)'
  ]
};
