export const DEFAULT_POSE_PROMPTS: { [group: string]: string[] } = {
  Posture: [
    'kneeling',
    'on one knee',
    'lying',
    'crossed legs',
    'fetal position',
    'on back',
    'on side',
    'on stomach',
    'sitting',
    'butterfly sitting',
    'crossed legs',
    'figure four sitting',
    'indian style',
    'hugging own legs',
    'lotus position',
    'seiza',
    'sitting on lap',
    'sitting on person',
    'straddling',
    'thigh straddling',
    'upright straddle',
    'wariza',
    'yokozuwari',
    'standing',
    'balancing',
    'crossed legs',
    'legs apart',
    'standing on one leg',
    'balancing',
    'crawling',
    'jumping',
    'running',
    'walking',
    'wallwalking',
    'all fours',
    'top-down bottom-up',
    'prostration',
    'chest stand',
    'cowering',
    'crucifixion',
    'faceplant',
    'fighting stance',
    'battoujutsu stance',
    'full scorpion',
    'reclining',
    'squatting',
    'stretching',
    'superhero landing',
    'upside-down',
    'handstand',
    'headstand',
    'yoga',
    'scorpion pose'
  ],
  'Head posture': ['head down', 'head tilt'],
  'Torso posture': [
    'arched back',
    'bent back',
    'bent over',
    'leaning back',
    'leaning forward',
    'slouching',
    'sway back',
    'twisted torso'
  ],
  'Arm posture': [
    'arm behind back',
    'arms behind back',
    'arm up',
    'arm behind head',
    'victory pose',
    'arms up',
    'arms behind head',
    'outstretched arm',
    'outstretched arms',
    'spread arms',
    'arm at side',
    'arms at sides',
    'interlocked fingers',
    'own hands clasped',
    'own hands together',
    'star hands'
  ],
  'Two hand gestures': [
    'air quotes',
    'carry me',
    'clenched hands',
    'cupping hands',
    'double finger gun',
    'double v',
    'fidgeting',
    'finger counting',
    'finger frame',
    'fist bump',
    'fist in hand',
    'heart arms',
    'heart hands',
    'heart hands duo',
    'heart hands trio',
    'high five',
    'horns pose',
    'noogie',
    'own hands clasped',
    'palm-fist greeting',
    'palm-fist tap',
    'penetration gesture',
    'pinky swear',
    'rabbit pose',
    'shadow puppet',
    'steepled fingers',
    'tsuki ni kawatte oshioki yo',
    'x arms',
    'x fingers'
  ],
  'One hand gestures': [
    'akanbe',
    'beckoning',
    'hair twirling',
    'index finger raised',
    'middle finger',
    'pinky out',
    'pointing',
    'pointing at self',
    'pointing at viewer',
    'pointing down',
    'pointing forward',
    'pointing up',
    'kamina pose',
    'saturday night fever',
    'shushing',
    'slit throat (gesture)',
    'thumbs down',
    'thumbs up',
    'crossed fingers',
    'finger gun',
    'finger heart',
    'fox shadow puppet',
    'inward v',
    'shaka sign',
    'two-finger salute',
    'middle w',
    'money gesture',
    'ok sign',
    'claw pose',
    'facepalm',
    'ohikaenasutte',
    'open hand',
    'reaching',
    'salute',
    'spread fingers',
    'stop (gesture)',
    'straight-arm salute',
    'vulcan salute',
    'waving',
    'clenched hand',
    'fig sign',
    'paw pose',
    'power fist',
    'raised fist',
    'beckoning',
    'cunnilingus gesture',
    'fellatio gesture',
    'handjob gesture',
    'hat tip',
    'oral invitation',
    'oral simulation',
    'shocker (gesture)',
    'stroking own chin',
    'v over eye',
    'v over mouth'
  ],
  'Leg posture': [
    'crossed ankles',
    'legs folded',
    'leg up',
    'legs up',
    'knees to chest',
    'legs over head',
    'leg lift',
    'outstretched leg',
    'split',
    'pigeon pose',
    'standing split',
    'spread legs',
    'watson cross',
    'knees together feet apart',
    'knees apart feet together',
    'dorsiflexion',
    'pigeon-toed',
    'plantar flexion',
    'tiptoes',
    'tiptoe kiss'
  ],
  Poses: [
    'animal pose',
    'rabbit pose',
    'horns pose',
    'paw pose',
    'claw pose',
    'archer pose',
    "bras d'honneur",
    'body bridge',
    'contrapposto',
    'dojikko pose',
    'inugami-ke no ichizoku pose',
    'letter pose',
    'ojou-sama pose',
    'saboten pose',
    'symmetrical hand pose',
    'victory pose',
    'villain pose',
    'zombie pose',
    'air guitar',
    'bowing',
    'curtsey',
    'hand glasses',
    'heart tail',
    'heart tail duo',
    'kuji-in',
    'orchid fingers',
    'shrugging',
    'toe-point'
  ],
  'Two character pose': [
    'ass-to-ass',
    'back-to-back',
    'belly-to-belly',
    'cheek-to-breast',
    'cheek-to-cheek',
    'eye contact',
    'face-to-face',
    'forehead-to-forehead',
    'head on chest',
    'heads together',
    'holding hands',
    'leg lock',
    'over the knee',
    'nipple-to-nipple',
    'noses touching',
    'shoulder-to-shoulder',
    'tail lock',
    'arm hug',
    'hug from behind',
    'waist hug',
    'hugging tail',
    'wing hug'
  ],
  Foreplay: [
    'footjob',
    'double footjob',
    'implied footjob',
    'cooperative footjob',
    'shoejob',
    'feet',
    'licking foot',
    'foot worship',
    'smelling feet',
    'frottage',
    'dry humping',
    'armpit sex',
    'grinding',
    'backjob',
    'buttjob',
    'cooperative grinding',
    'kneepit sex',
    'paizuri',
    'autopaizuri',
    'cooperative paizuri',
    'handsfree paizuri',
    'naizuri',
    'paizuri over clothes',
    'paizuri on lap',
    'paizuri under clothes',
    'perpendicular paizuri',
    'stealth paizuri',
    'straddling paizuri',
    'thigh sex',
    'groping',
    'ass grab',
    "grabbing another's breast",
    'guided breast grab',
    'pectoral grab',
    'guided pectoral grab',
    'nipple tweak',
    'crotch grab',
    'guided crotch grab',
    'grabbing own breast',
    'torso grab',
    'hairjob',
    'handjob',
    'caressing testicles',
    'double handjob',
    'cooperative handjob',
    'nursing handjob',
    'cuddling handjob',
    'reverse nursing handjob',
    'reach-around',
    'two-handed handjob',
    'masturbation',
    'clothed masturbation',
    'crotch rub',
    'building sex',
    'pillow sex',
    'teddy bear sex',
    'table humping',
    'female masturbation',
    'futanari masturbation',
    'implied masturbation',
    'male masturbation',
    'mutual masturbation',
    'stealth masturbation',
    'tail masturbation',
    'tail',
    'tail insertion',
    'tail masturbation',
    'tailjob',
    'oral',
    'anilingus',
    'rusty trombone',
    'breast sucking',
    'cunnilingus',
    'autocunnilingus',
    'implied cunnilingus',
    'fellatio',
    'autofellatio',
    'deepthroat',
    'implied fellatio',
    'irrumatio',
    'cooperative fellatio',
    'multiple penis fellatio',
    'hug and suck',
    'licking testicle',
    'sitting on face',
    'testicle sucking'
  ],
  'Sexual positions': [
    '69',
    'doggystyle',
    'bent over',
    'prone bone',
    'top-down bottom-up',
    'spitroast',
    'reverse spitroast',
    'spooning',
    'on side',
    'girl on top',
    'amazon position',
    'cowgirl position',
    'reverse cowgirl position',
    'reverse upright straddle',
    'upright straddle',
    'boy on top',
    'anvil position',
    'folded / knees to chest / legs over head / legs up',
    'missionary',
    'mating press',
    'suspended congress',
    'reverse suspended congress',
    'full nelson',
    'piledriver'
  ],
  Bondage: [
    'bound arms',
    'bound feet',
    'bound legs',
    'bound calves',
    'bound knees',
    'bound thighs',
    'bound torso',
    'bound wrists',
    'box tie',
    'frogtie',
    'hogtie',
    'separated arms',
    'separated legs',
    'separated wrists',
    'shrimp tie',
    'strappado',
    'suspension',
    'cuffs-to-collar'
  ],
  'Group Sex': [
    'group sex',
    'bisexual',
    'bisexual female',
    'bisexual male',
    'blue plate special',
    'daisy chain',
    'gangbang',
    'double penetration',
    'triple penetration',
    'love train',
    'cooperative fellatio',
    'cooperative footjob',
    'cooperative breast smother',
    'orgy',
    'reverse spitroast',
    'spitroast',
    'teamwork',
    'threesome',
    'MMF threesome',
    'FFM threesome',
    'MMM threesome',
    'FFF threesome'
  ],
  Penetration: [
    'cervical penetration',
    'covered penetration',
    'deep penetration',
    'inflation',
    'cum inflation',
    'big belly',
    'enema',
    'large insertion',
    'stomach bulge',
    'multiple insertions',
    'nipple penetration',
    'nosejob',
    'object insertion',
    'vaginal object insertion',
    'anal object insertion',
    'urethral insertion',
    'sounding',
    'fingering',
    'anal fingering',
    'prostate milking',
    'fingering through clothes',
    'fingering through panties',
    'implied fingering',
    'fisting',
    'anal fisting',
    'self fisting',
    'sex',
    'after sex',
    'after anal',
    'after buttjob',
    'after fellatio',
    'after fingering',
    'after frottage',
    'after insertion',
    'after masturbation',
    'after oral',
    'after paizuri',
    'after rape',
    'after urethral',
    'after vaginal',
    'afterglow',
    'clothed after sex',
    'anal',
    'double anal',
    'imminent anal',
    'pegging',
    'triple anal',
    'clothed sex',
    'guided penetration',
    'happy sex',
    'imminent penetration',
    'implied sex',
    'navel sex',
    'sex from behind',
    'skull fucking',
    'ear sex',
    'penis in eye',
    'tentacle sex',
    'underwater sex',
    'vaginal',
    'after vaginal',
    'double vaginal',
    'imminent vaginal',
    'triple vaginal'
  ],
  Verbs: [
    'aiming',
    'aiming at viewer',
    'animal milking',
    'apologizing',
    'applying makeup',
    'balancing',
    'bathing',
    'beckoning',
    'begging',
    'biting',
    'ass biting',
    'breast biting',
    'cheek biting',
    'ear biting',
    'finger biting',
    'foreskin biting',
    'glove biting',
    "biting another's hand",
    'head biting',
    'biting own lip',
    'nail biting',
    'penis biting',
    'tail biting',
    'thumb biting',
    'blinking',
    'blocking',
    'bouncing',
    'bouncing breasts',
    'bowing',
    'breaking',
    'breastfeeding',
    'breathing',
    'heavy breathing',
    'panting',
    'bubble blowing',
    'bumping',
    'carrying',
    'catching',
    'chasing',
    'cheering',
    'stroking own chin',
    'cleaning',
    'dishwashing',
    'sweeping',
    'climbing',
    'comforting',
    'concentrating',
    'cooking',
    'baking',
    'chocolate making',
    'roasting',
    'stirring',
    'coughing',
    'covering privates',
    'cowering',
    'crawling',
    'crushing',
    'crying',
    'sobbing',
    'cuddling',
    'cupping',
    'cutting',
    'wrist cutting',
    'dancing',
    'pole dancing',
    'diaper changing',
    'digging',
    'diving',
    'dodging',
    'dragging',
    'dreaming',
    'dressing',
    'forced dressing',
    'undressing',
    'drinking',
    'dripping',
    'driving',
    'drooling',
    'dropping',
    'drying',
    'dual wielding',
    'quadruple wielding',
    'triple wielding',
    'dying',
    'ear cleaning',
    'eating',
    'chewing',
    'swallowing',
    'tasting',
    'eavesdropping',
    'elbowing',
    "drawing on another's face",
    'fainting',
    'falling',
    'fanning',
    'fan speaking',
    'fanning crotch',
    'fanning face',
    'feeding',
    'pov feeding',
    'fidgeting',
    'fighting',
    'fingering',
    'anal fingering',
    'firing',
    'fisting',
    'anal fisting',
    'flailing',
    'flapping',
    'flirting',
    'floating',
    'flying',
    'gardening',
    'watering',
    'giving',
    'glaring',
    'glowing',
    'grabbing',
    'grinding',
    'cooperative grinding',
    'groping',
    'hairdressing',
    'brushing hair',
    'hair tucking',
    'hair twirling',
    'hanging',
    'hatching',
    'healing',
    'hiding',
    'hitting',
    'holding',
    'humping',
    'dry humping',
    'imagining',
    'imitating',
    'juggling',
    'jumping',
    'hopping',
    'pouncing',
    'kicking',
    'kneeing',
    'knocking',
    'landing',
    'laughing',
    'giggling',
    'launching',
    'leaning',
    'licking',
    'licking armpit',
    'licking breast',
    "licking another's cheek",
    'licking cum',
    'licking ear',
    'licking eye',
    "licking another's face",
    'licking finger',
    'licking floor',
    'licking foot',
    'licking blade',
    'licking leg',
    'licking navel',
    'licking nipple',
    'licking panties',
    'licking testicle',
    'licking thigh',
    'lifting',
    'looking',
    'looking at viewer',
    'looking away',
    'looking back',
    'looking down',
    'looking up',
    'lying',
    'measuring',
    'bust measuring',
    'penis measuring',
    'waist measuring',
    'melting',
    'mind reading',
    'moaning',
    'multitasking',
    'nose picking',
    'opening',
    'pantsing',
    'patting',
    'peeing',
    'bedwetting',
    'peeking',
    'peeling',
    'headpat',
    'pinching',
    'cheek pinching',
    'pitching',
    'playing',
    'playing games',
    'playing instrument',
    'playing sports',
    'pointing',
    'pointing at viewer',
    'poking',
    'cheek poking',
    'polishing',
    'pouring',
    'decantering',
    'praying',
    'presenting',
    'programming',
    'protecting',
    'pulling',
    'punching',
    'pushing',
    'rappelling',
    'reaching',
    'reading',
    'reloading',
    'repairing',
    'resisting',
    'resting',
    'riding',
    'broom riding',
    'umbrella riding',
    'ripping',
    'roaring',
    'rolling',
    'rubbing',
    'crotch rub',
    'running',
    'scratching',
    'screaming',
    'searching',
    'shading eyes',
    'shaking',
    'sharing',
    'shaving',
    'shopping',
    'shouting',
    'shushing',
    'singing',
    'sinking',
    'sitting',
    'reclining',
    'sketching',
    'skipping',
    'slashing',
    'sleeping',
    'sliding',
    'slipping',
    'smelling',
    'smelling clothes',
    'smelling pantyhose',
    'smelling underwear',
    'smoking',
    'sneezing',
    'snowing',
    'spanking',
    'spilling',
    'spinning',
    'pen spinning',
    'spitting',
    'splashing',
    'spooning',
    'spraying',
    'squeezing',
    'squinting',
    'squirting liquid',
    'stacking',
    'standing',
    'staring',
    'stepping',
    'stomping',
    'strangling',
    'struggling',
    'studying',
    'sucking',
    'blood sucking',
    'breast sucking',
    'self breast sucking',
    'finger sucking',
    'thumb sucking',
    'toe sucking',
    'sulking',
    'summoning',
    'sunbathing',
    'surfing',
    'broom surfing',
    'sky surfing',
    'swaying',
    'swinging',
    'tail fondling',
    'talking',
    'sleep talking',
    'teaching',
    'text messaging',
    'thinking',
    'throwing',
    'tickling',
    'foot tickling',
    'touching',
    'training',
    'trembling',
    'trolling',
    'twitching',
    'tying',
    'scarf tying',
    'tying footwear',
    'untying',
    'typing',
    'unsheathing',
    'unzipping with mouth',
    'vomiting',
    'wading',
    'skinny dipping',
    'waiting',
    'walking',
    'pet walking',
    'rope walking',
    'wallwalking',
    'warming',
    'washing',
    'body soaping',
    'watching',
    'watching television',
    'waving',
    'whipping',
    'whisking',
    'whispering',
    'whistling',
    'working',
    'wringing',
    'zipping',
    'unzipping'
  ]
};
