export const DEFAULT_ATTIRE_PROMPTS: { [group: string]: string[] } = {
  Headwear: [
    'balaclava',
    'baseball cap',
    'camouflage headwear',
    'checkered headwear',
    'crown',
    'forehead protector',
    'frilled hat',
    'habit',
    'hachimaki',
    'hair bow',
    'hair ribbon',
    'hairband',
    'head scarf',
    'headband',
    'headdress',
    'hijab',
    'honggaitou',
    'jester cap',
    'maid headdress',
    'military hat',
    'mini hat',
    'mongkhon',
    'multicolored headwear',
    'native american headdress',
    'nejiri hachimaki',
    'police hat',
    'print headwear',
    'school hat',
    'straw hat',
    'sweatband',
    'tiara',
    'veil',
    'warbonnet'
  ],
  'Shirts and Topwear': [
    'blouse',
    'frilled shirt',
    'sleeveless shirt',
    'bustier',
    'crop top',
    'camisole',
    'cardigan',
    'cardigan vest',
    'coat',
    'duffel coat',
    'fur coat',
    'fur-trimmed coat',
    'long coat',
    'overcoat',
    'peacoat',
    'raincoat',
    'yellow raincoat',
    'transparent raincoat',
    'trench coat',
    'winter coat',
    'compression shirt',
    'corset',
    'dress',
    'halterneck',
    'criss-cross halter',
    'halterneck',
    'hoodie',
    'jacket',
    'blazer',
    'cropped jacket',
    'letterman jacket',
    'safari jacket',
    'suit jacket',
    'sukajan',
    'trench coat',
    'poncho',
    'raglan sleeves',
    'sash',
    'shoulder sash',
    'stole',
    'shirt',
    'collared shirt',
    'dress shirt',
    'off-shoulder shirt',
    'sleeveless shirt',
    'striped shirt',
    't-shirt',
    'shrug',
    'surcoat',
    'sweater',
    'pullover',
    'turtleneck',
    'sleeveless turtleneck',
    'sweater dress',
    'ribbed sweater',
    'aran sweater',
    'tabard',
    'tailcoat',
    'tank top',
    'stringer',
    'tube top',
    'bandeau',
    'underbust',
    'vest',
    'sweater vest',
    'waistcoat'
  ],
  'Pants and Bottomwear': [
    'bloomers',
    'buruma',
    'chaps',
    'kilt',
    'pants',
    'bell-bottoms',
    'capri pants',
    'detached pants',
    'jeans',
    'cutoff jeans',
    'lowleg pants',
    'pants rolled up',
    'yoga pants',
    'pelvic curtain',
    'petticoat',
    'sarong',
    'shorts',
    'bike shorts',
    'denim shorts',
    'dolphin shorts',
    'gym shorts',
    'lowleg shorts',
    'micro shorts',
    'short shorts',
    'shorts under skirt',
    'skirt',
    'bubble skirt',
    'high-waist skirt',
    'high-low skirt',
    'long skirt',
    'lowleg skirt',
    'microskirt',
    'miniskirt',
    'overall skirt',
    'plaid skirt ',
    'tartan',
    'kilt skirt',
    'pleated skirt',
    'suspender skirt'
  ],
  'Legs and Feet': [
    'garter belt',
    'garter straps',
    'legwear garter',
    'kneehighs',
    'leggings',
    'leg warmers',
    'over-kneehighs',
    'pantyhose',
    'thighband pantyhose',
    'socks',
    'ankle socks',
    'bobby socks',
    'loose socks',
    'tabi',
    'toe socks',
    'tube socks',
    'thighhighs',
    'thigh strap'
  ],
  Footwear: [
    'boots',
    'ankle boots',
    'armored boots',
    'cowboy boots',
    'spurs',
    'knee boots',
    'high heel boots',
    'lace-up boots',
    'rubber boots',
    'thigh boots',
    'work boots',
    'cross-laced footwear',
    'dress shoes',
    'flats',
    'footwear ribbon',
    'high heels',
    'loafers',
    'kiltie loafers',
    'mary janes',
    'platform footwear',
    'pointy footwear',
    'pumps',
    'sandals',
    'cross-laced sandals',
    'flip-flops',
    'gladiator sandals',
    'geta',
    'okobo',
    'waraji',
    'zouri',
    'oxfords',
    'saddle shoes',
    'monk shoes',
    'slippers',
    'animal slippers',
    'ballet slippers',
    'crocs',
    'uwabaki',
    'sneakers',
    'high tops',
    'converse',
    'toeless footwear',
    'uwabaki',
    'winged footwear',
    'wedge heels'
  ],
  Dresses: [
    'argyle dress',
    'checkered dress',
    'flag dress',
    'plaid dress',
    'polka dot dress',
    'print dress',
    'striped dress',
    'vertical-striped dress',
    'pinstripe dress',
    'armored dress',
    'backless dress',
    'crinoline',
    'collared dress',
    'frilled dress',
    'fur-trimmed_dress',
    'half-dress',
    'halter dress',
    'highleg dress',
    'high-low skirt',
    'hobble dress',
    'impossible dress',
    'lace-trimmed dress',
    'latex dress',
    'layered dress',
    'long dress',
    'off-shoulder dress',
    'pleated dress',
    'plunging neckline',
    'ribbed dress',
    'ribbon-trimmed_dress',
    'short dress',
    'side slit',
    'taut dress',
    'see-through dress',
    'sleeveless dress',
    'strapless dress',
    'cake dress',
    'china dress',
    'coat dress',
    'cocktail dress',
    'denim dress',
    'dirndl',
    'evening gown',
    'flowing dress',
    'funeral dress',
    'gown',
    'mermaid dress',
    'negligee',
    'nightgown',
    'pencil dress',
    'pinafore dress',
    'sailor dress',
    'santa dress',
    'sundress',
    'sweater dress',
    'tennis dress',
    'trapeze dress',
    'tube dress',
    'vietnamese dress',
    'wedding dress'
  ],
  Lingerie: [
    'Lingerie',
    'Babydoll',
    'Bodystocking',
    'Bra',
    'checkered bra',
    'lace bra',
    'lace-trimmed bra',
    'plaid bra',
    'polka dot bra',
    'print bra',
    'strawberry bra',
    'striped bra',
    'vertical-striped bra',
    'adhesive bra',
    'belt bra',
    'bow bra',
    'bridgeless bra',
    'cupless bra',
    'frilled bra',
    'shelf bra',
    'sports bra',
    'strapless bra',
    'training bra',
    'front-tie bra',
    'front-hook bra',
    'Bustier',
    'Camisole',
    'Chemise',
    'Corset',
    'Fishnets',
    'garter straps',
    'Garter belt',
    'Lace',
    'Nightgown',
    'Panties',
    'bear panties',
    'rabbit panties',
    'cat panties',
    'checkered panties',
    'lace panties',
    'lace-trimmed panties',
    'plaid panties',
    'polka dot panties',
    'print panties',
    'strawberry panties',
    'striped panties',
    'vertical-striped panties',
    'latex panties',
    'leaf panties',
    'backless panties',
    'c-string',
    'crotchless panties',
    'strapless bottom',
    'Boyshort panties',
    'Strapless bottom',
    'Teddy',
    'Thighhighs',
    'Thong',
    'G-string',
    'Pearl thong',
    'Male Underwear',
    'Boxers',
    'Briefs',
    'Boxer briefs',
    'Bikini briefs',
    'Jockstrap',
    'Ball bra',
    'Penis sheath'
  ],
  'BDSM and Exposure': [
    'Ass Cutout',
    'Blindfold',
    'Bodysuit',
    'Clamp',
    'Crotchless',
    'Gimp suit',
    'Latex',
    'Monoglove',
    'anal hook',
    'assless swimsuit',
    'backless panties',
    'backless pants',
    'ball gag',
    'bit gag',
    'blindfold',
    'bondage outfit',
    'breastless clothes',
    'chain',
    'chastity belt',
    'chastity bra',
    'chastity cage',
    'cleave gag',
    'clitoris clamp',
    'clitoris leash',
    'collar',
    'crotch rope',
    'crotchless bloomers',
    'crotchless buruma',
    'crotchless leotard',
    'crotchless panties',
    'crotchless pants',
    'crotchless pantyhose',
    'crotchless swimsuit',
    'cuffs',
    'cupless bikini',
    'cupless bra',
    'gag harness',
    'gag',
    'gimp suit',
    'handcuffs',
    'hobble',
    'judas cradle',
    'leash on penis',
    'leash',
    'nipple chain',
    'nipple clamps',
    'nipple leash',
    'nippleless clothes',
    'nose hook',
    'panty gag',
    'pillory',
    'plug gag',
    'revealing clothes',
    'reverse bikini armor',
    'reverse bunnysuit',
    'reverse outfit',
    'riding crop',
    'ring gag',
    'rope',
    'shackles',
    'sounding',
    'spreader bar',
    'stocks',
    'tape gag',
    'tongue clamp',
    'whip',
    'wooden horse'
  ],
  'Sex toys': [
    'anal beads',
    'anal tail',
    'artificial vagina',
    'artificial ass',
    'tenga',
    'butt plug',
    'aneros',
    'butt plug tail',
    'jewel butt plug',
    'cock ring',
    'dildo',
    'double dildo',
    'huge dildo',
    'dragon dildo',
    'horse dildo',
    'spiked dildo',
    'strap-on',
    'suction cup dildo',
    'dildo riding',
    'food insertion',
    'dildo gag',
    'dildo harness',
    'dildo under panties',
    'prostate massager',
    'breast pump',
    'clitoris pump',
    'sex machine',
    'sex toy',
    'sounding',
    'catheter',
    'urethral beads',
    'too many sex toys',
    'ben wa balls',
    'vibrator',
    'rabbit vibrator',
    'butterfly vibrator',
    'egg vibrator',
    'hitachi magic wand',
    'remote control vibrator',
    'riding machine',
    'sybian',
    'public vibrator',
    'vibrator under clothes',
    'vibrator in leg garter',
    'vibrator in thighhighs',
    'vibrator in thigh strap',
    'vibrator under panties',
    'vibrator under pantyhose',
    'vibrator on nipple',
    'vibrator in anus',
    'vibrator on penis'
  ],
  Cutouts: [
    'armpit cutout',
    'ass cutout',
    'back cutout',
    'cleavage cutout',
    'crotch cutout',
    'hip vent',
    'leg cutout',
    'shoulder cutout',
    'stomach cutout',
    'cutout above navel',
    'navel cutout',
    'cutout below navel',
    'tail through clothes',
    'thigh cutout',
    'underboob cutout'
  ],
  'Uniforms and Costumes': [
    'apron',
    'armor',
    'armored dress',
    'bikini armor',
    'band uniform',
    'cape',
    'capelet',
    'hood',
    'side cape',
    'cassock',
    'cheerleader',
    'costume',
    'ghost costume',
    'formal',
    'suit',
    'business suit',
    'pant suit',
    'skirt suit',
    'tuxedo',
    'gym uniform',
    'buruma',
    'habit',
    'harem outfit',
    'loincloth',
    'hazmat suit',
    'hev suit',
    'kigurumi',
    'animal costume',
    'bear costume',
    'boar costume',
    'cat costume',
    'cow costume',
    'dog costume',
    'monkey costume',
    'mouse costume',
    'panda costume',
    'penguin costume',
    'pig costume',
    'rabbit costume',
    'reindeer costume',
    'seal costume',
    'sheep costume',
    'tiger costume',
    'maid',
    'miko',
    'nontraditional miko',
    'military uniform',
    'overalls',
    'pajamas',
    'pilot suit',
    'plugsuit',
    'sailor',
    'naval uniform',
    'santa costume',
    'school uniform',
    'serafuku',
    'sailor uniform',
    'sailor dress',
    'gakuran',
    'meiji schoolgirl uniform',
    'shosei',
    'track suit',
    'sweatpants',
    'sweater',
    'tutu',
    'waitress',
    'cowboy western',
    'cowboy outfit'
  ],
  'Swimsuits and Bodysuits': [
    'bikesuit',
    'racing suit',
    'bodystocking',
    'bodysuit',
    'jumpsuit',
    'short jumpsuit',
    'leotard',
    'see-through leotard',
    'strapless leotard',
    'playboy bunny',
    'swimsuit',
    'competition swimsuit',
    'slingshot swimsuit',
    'school swimsuit',
    'bikini',
    'leaf bikini',
    'string bikini',
    'micro bikini',
    'side-tie bikini bottom',
    'lowleg bikini',
    'thong bikini',
    'venus bikini',
    'sports bikini',
    'tankini',
    'criss-cross halter',
    'swim briefs ',
    'speedo',
    'jammers',
    'legskin',
    'rash guard',
    'robe',
    'bathrobe',
    'open robe',
    'kesa',
    'romper',
    'sarong',
    'tunic',
    'unitard'
  ],
  'Traditional Clothing': [
    'chinese clothes',
    'changpao',
    'china dress',
    'cheongsam',
    'qipao',
    'fengguan',
    'hanfu',
    'longpao',
    'tangzhuang',
    'dirndl',
    'japanese clothes',
    'fundoshi',
    'yamakasa',
    'geta',
    'hakama',
    'hakama skirt',
    'hakama short skirt',
    'hakama pants',
    'kimono',
    'furisode',
    'layered kimono',
    'short kimono',
    'uchikake',
    'wedding kimono',
    'yukata',
    'haori',
    'happi',
    'chanchanko',
    'dotera',
    'hanten',
    'kimono skirt',
    'miko',
    'nontraditional miko',
    'sarashi',
    'Midriff sarashi',
    'Chest sarashi',
    'Budget sarashi',
    'Undone sarashi',
    'straw cape',
    'mino boushi',
    'tabi',
    'tasuki',
    'korean clothes',
    'hanbok',
    'vietnamese dress'
  ],
  'Styles and Patterns': [
    'argyle',
    'camouflage',
    'checkered',
    'floral print',
    'gingham',
    'houndstooth',
    'pinstripe pattern',
    'plaid',
    'tartan',
    'polka dot',
    'striped',
    'multicolored stripes',
    'double vertical stripe',
    'animal print',
    'bat print',
    'bear print',
    'butterfly print',
    'cow print',
    'leopard print',
    'tiger print',
    'snake print',
    'clover print',
    'crescent print',
    'floral print',
    'rose print',
    'camellia print',
    'cherry blossom print',
    'chrysanthemum print',
    'lily print',
    'morning glory print',
    'peony print',
    'plum blossom print',
    'spider lily print',
    'sunflower print',
    'food print',
    'fruit pattern',
    'apple print',
    'blueberry print',
    'cherry print',
    'kiwi print',
    'lemon print',
    'pineapple print',
    'orange print',
    'strawberry print',
    'watermelon print',
    'leaf print',
    'maple leaf print',
    'moon print',
    'musical note print',
    'paw print',
    'petal print',
    'piano print',
    'sparkle print',
    'triangle print',
    'space print',
    'starry sky print',
    'star print',
    'wave print',
    'wing print'
  ],
  'Jewelry and Accessories - Head': [
    'earrings',
    'hoop earrings',
    'stud earrings',
    'earclip',
    'glasses',
    'monocle',
    'hair ornament',
    'hair beads',
    'hair bobbles',
    'hairclip',
    'hairpin',
    'hair scrunchie',
    'hair stick',
    'kanzashi',
    'mask',
    'plague doctor mask',
    'surgical mask'
  ],
  'Jewelry and Accessories - Neck': [
    'ascot',
    'bowtie',
    'choker',
    'collar',
    'cross tie',
    'epaulettes',
    'feather boa',
    'lapels',
    'lapel pin',
    'neck ruff',
    'neckerchief',
    'necklace',
    'necktie',
    'tie clip',
    'neck ribbon',
    'scarf',
    'shawl',
    'stole'
  ],
  'Jewelry and Accessories - Limbs': [
    'anklet',
    'arm belt',
    'armband',
    'armlet',
    'bracelet',
    'bangle',
    'spiked bracelet',
    'bridal gauntlets',
    'detached sleeves',
    'arm warmers',
    'fingernails',
    'gloves',
    'boxing gloves',
    'elbow gloves',
    'fingerless gloves',
    'bridal gauntlets',
    'spiked gloves',
    'yugake',
    'mittens',
    'leg belt',
    'ring',
    'claw ring',
    'wedding ring',
    'wedding ring',
    'thighlet',
    'wide sleeves',
    'wristband',
    'wrist cuffs',
    'wrist scrunchie'
  ],
  'Jewelry and Accessories - Torso': [
    'aiguillette',
    'badge',
    'belly chain',
    'belt',
    'buckle',
    'belt chain',
    'sam browne belt',
    'boutonniere',
    'brooch',
    'buttons',
    'large buttons',
    'button badge',
    'buttoned cuffs',
    'collar chain',
    'corsage',
    'cuff links',
    'pentacle',
    'sarong',
    'sash',
    'shoulder sash',
    'suspenders',
    'tassel',
    'watch',
    'pocket watch',
    'zipper'
  ],
  Piercings: [
    'Ear piercing',
    'Industrial piercing',
    'Ear chain',
    'Animal ear piercing',
    'Eyebrow piercing',
    'Anti-eyebrow piercing',
    'Eyelid piercing',
    'Lip piercing',
    'Labret piercing',
    'Neck Piercing',
    'Nose piercing',
    'Bridge piercing',
    'Tongue piercing',
    'Areola piercing',
    'Back piercing',
    'Corset piercing',
    'Collarbone piercing',
    'Navel piercing',
    'Nipple piercing',
    'Nipple bar',
    'Nipple chain',
    'Nipple lock',
    'Nipple rings',
    'Nipple stretcher',
    'Nipple jewelry',
    'Pussy piercing',
    'Clitoris piercing',
    'Clitoris ring',
    'Labia piercing',
    'Fourchette piercing',
    'Pussy jewelry',
    'Penis piercing',
    'Ampallang',
    'Dydoe',
    'Foreskin piercing',
    'Frenulum piercing',
    'Lorum piercing',
    'Prince Albert',
    'Guiche piercing',
    'Scrotum piercing'
  ]
};
