import { Prompt } from './prompt';

export const DEFAULT_FACE_PROMPTS: { [group: string]: Prompt[] } = {
  Ears: [
    Prompt.create('animal ears'),
    Prompt.create('bat ears'),
    Prompt.create('bear ears'),
    Prompt.create('rabbit ears'),
    Prompt.create('cat ears'),
    Prompt.create('cow ears'),
    Prompt.create('deer ears'),
    Prompt.create('dog ears'),
    Prompt.create('ferret ears'),
    Prompt.create('fox ears'),
    Prompt.create('goat ears'),
    Prompt.create('horse ears'),
    Prompt.create('lion ears'),
    Prompt.create('monkey ears'),
    Prompt.create('mouse ears'),
    Prompt.create('panda ears'),
    Prompt.create('pikachu ears'),
    Prompt.create('pig ears'),
    Prompt.create('raccoon ears'),
    Prompt.create('sheep ears'),
    Prompt.create('squirrel ears'),
    Prompt.create('tiger ears'),
    Prompt.create('wolf ears'),
    Prompt.create('fake animal ears'),
    Prompt.create('animal ear headphones'),
    Prompt.create('bear ear headphones'),
    Prompt.create('cat ear headphones'),
    Prompt.create('rabbit ear headphones'),
    Prompt.create('hair ears')
  ],
  'Eyes Color': [
    Prompt.create('aqua eyes'),
    Prompt.create('black eyes'),
    Prompt.create('blue eyes'),
    Prompt.create('brown eyes'),
    Prompt.create('green eyes'),
    Prompt.create('grey eyes'),
    Prompt.create('orange eyes'),
    Prompt.create('purple eyes'),
    Prompt.create('pink eyes'),
    Prompt.create('red eyes'),
    Prompt.create('white eyes'),
    Prompt.create('yellow eyes'),
    Prompt.create('amber eyes'),
    Prompt.create('heterochromia'),
    Prompt.create('multicolored eyes')
  ],
  Pupils: [
    Prompt.create('ringed eyes'),
    Prompt.create('aqua pupils'),
    Prompt.create('blue pupils'),
    Prompt.create('brown pupils'),
    Prompt.create('green pupils'),
    Prompt.create('grey pupils'),
    Prompt.create('orange pupils'),
    Prompt.create('pink pupils'),
    Prompt.create('purple pupils'),
    Prompt.create('red pupils'),
    Prompt.create('white pupils'),
    Prompt.create('yellow pupils'),
    Prompt.create('constricted pupils'),
    Prompt.create('dilated pupils'),
    Prompt.create('extra pupils'),
    Prompt.create('horizontal pupils'),
    Prompt.create('no pupils'),
    Prompt.create('slit pupils'),
    Prompt.create('symbol-shaped pupils'),
    Prompt.create('diamond-shaped pupils'),
    Prompt.create('flower-shaped pupils'),
    Prompt.create('heart-shaped pupils'),
    Prompt.create('star-shaped pupils'),
    Prompt.create('cross-shaped pupils'),
    Prompt.create('x-shaped pupils'),
    Prompt.create('mismatched pupils')
  ],
  Sclera: [
    Prompt.create('blue sclera'),
    Prompt.create('black sclera'),
    Prompt.create('blank eyes'),
    Prompt.create('bloodshot eyes'),
    Prompt.create('green sclera'),
    Prompt.create('mismatched sclera'),
    Prompt.create('no sclera'),
    Prompt.create('orange sclera'),
    Prompt.create('red sclera'),
    Prompt.create('yellow sclera')
  ],
  'Other Eye Features': [
    Prompt.create('bags under eyes'),
    Prompt.create('bruised eye'),
    Prompt.create('flaming eyes'),
    Prompt.create('glowing eyes'),
    Prompt.create('glowing eye'),
    Prompt.create('amphibian eyes'),
    Prompt.create('button eyes'),
    Prompt.create('cephalopod eyes'),
    Prompt.create('compound eyes'),
    Prompt.create('horizontal pupils'),
    Prompt.create('missing eye'),
    Prompt.create('one-eyed'),
    Prompt.create('third eye'),
    Prompt.create('extra eyes'),
    Prompt.create('no eyes'),
    Prompt.create('artificial eye'),
    Prompt.create('glass eye'),
    Prompt.create('mechanical eye'),
    Prompt.create('asymmetrical eyes'),
    Prompt.create('big eyes')
  ],
  Lips: [
    Prompt.create('Dry lips'),
    Prompt.create('Lip balm'),
    Prompt.create('Lip piercing'),
    Prompt.create('Lips print'),
    Prompt.create('Pouty lips'),
    Prompt.create('Puffy lips'),
    Prompt.create('Thick lips')
  ],
  'Drawing styles': [
    Prompt.create('chestnut mouth'),
    Prompt.create('constricted pupils'),
    Prompt.create('cross-eyed'),
    Prompt.create('dot mouth'),
    Prompt.create('dot nose'),
    Prompt.create('mouth drool'),
    Prompt.create('no nose'),
    Prompt.create('no mouth'),
    Prompt.create('rectangular mouth'),
    Prompt.create('sideways mouth'),
    Prompt.create('split mouth'),
    Prompt.create('wavy mouth'),
    Prompt.create('wide-eyed')
  ],
  Skin: [
    Prompt.create('Freckles'),
    Prompt.create('Dark skin'),
    Prompt.create('Pale skin'),
    Prompt.create('Tan'),
    Prompt.create('Tanlines'),
    Prompt.create('Sun tattoo'),
    Prompt.create('Sun burnt'),
    Prompt.create('Black skin'),
    Prompt.create('Blue skin'),
    Prompt.create('Green skin'),
    Prompt.create('Grey skin'),
    Prompt.create('Orange skin'),
    Prompt.create('Pink skin'),
    Prompt.create('Purple skin'),
    Prompt.create('Red skin'),
    Prompt.create('White skin'),
    Prompt.create('Yellow skin')
  ]
};
