import { Prompt } from './prompt';

export const DEFAULT_COMPOSITION_PROMPTS: { [group: string]: Prompt[] } = {
  'View Angle': [
    Prompt.create('dutch angle'),
    Prompt.create('from above'),
    Prompt.create('from behind'),
    Prompt.create('from below'),
    Prompt.create('from side'),
    Prompt.create('sideways'),
    Prompt.create('straight-on'),
    Prompt.create('upside-down')
  ],
  'Perspective / Depth': [
    Prompt.create('atmospheric perspective'),
    Prompt.create('fisheye'),
    Prompt.create('panorama'),
    Prompt.create('perspective'),
    Prompt.create('vanishing point')
  ],
  Composition: [
    Prompt.create('afterimage'),
    Prompt.create('outside border'),
    Prompt.create('fading border'),
    Prompt.create('rounded corners'),
    Prompt.create('viewfinder'),
    Prompt.create('chart'),
    Prompt.create('bust chart'),
    Prompt.create('character chart'),
    Prompt.create('reference sheet'),
    Prompt.create('diagram'),
    Prompt.create('move chart'),
    Prompt.create('relationship graph'),
    Prompt.create('seating chart'),
    Prompt.create('stats'),
    Prompt.create('collage'),
    Prompt.create('column lineup'),
    Prompt.create('out of frame'),
    Prompt.create('fake scrollbar'),
    Prompt.create('head out of frame'),
    Prompt.create('out-of-frame censoring'),
    Prompt.create('outside border'),
    Prompt.create('from outside'),
    Prompt.create('glitch'),
    Prompt.create('isometric'),
    Prompt.create('letterboxed'),
    Prompt.create('lineup'),
    Prompt.create('mosaic art'),
    Prompt.create('photomosaic'),
    Prompt.create('negative space'),
    Prompt.create('omake'),
    Prompt.create('partially underwater shot'),
    Prompt.create('pov'),
    Prompt.create('social media composition'),
    Prompt.create('symmetry'),
    Prompt.create('polar opposites'),
    Prompt.create('rotational symmetry'),
    Prompt.create('trim marks')
  ],
  'Subject matter': [
    Prompt.create('cityscape'),
    Prompt.create('everyone'),
    Prompt.create('absolutely everyone'),
    Prompt.create('landscape'),
    Prompt.create('nature'),
    Prompt.create('no humans'),
    Prompt.create('off-topic'),
    Prompt.create('scenery'),
    Prompt.create('still life'),
    Prompt.create('animal focus'),
    Prompt.create('armpit focus'),
    Prompt.create('ass focus'),
    Prompt.create('back focus'),
    Prompt.create('book focus'),
    Prompt.create('breast focus'),
    Prompt.create('cloud focus'),
    Prompt.create('eye focus'),
    Prompt.create('food focus'),
    Prompt.create('foot focus'),
    Prompt.create('hand focus'),
    Prompt.create('hip focus'),
    Prompt.create('male focus'),
    Prompt.create('navel focus'),
    Prompt.create('other focus'),
    Prompt.create('pectoral focus'),
    Prompt.create('solo focus'),
    Prompt.create('vehicle focus'),
    Prompt.create('text focus'),
    Prompt.create('thigh focus'),
    Prompt.create('weapon focus'),
    Prompt.create('vehicle focus'),
    Prompt.create('wind chime focus')
  ],
  Framing: [
    Prompt.create('face'),
    Prompt.create('portrait'),
    Prompt.create('upper body'),
    Prompt.create('lower body'),
    Prompt.create('cowboy shot'),
    Prompt.create('feet out of frame'),
    Prompt.create('full body'),
    Prompt.create('wide shot'),
    Prompt.create('very wide shot'),
    Prompt.create('close-up'),
    Prompt.create('cut-in'),
    Prompt.create('split crop'),
    Prompt.create('cropped legs'),
    Prompt.create('cropped torso'),
    Prompt.create('cropped arms'),
    Prompt.create('cropped shoulders'),
    Prompt.create('cropped head')
  ],
  Styles: [
    Prompt.create('abstract'),
    Prompt.create('art deco'),
    Prompt.create('art nouveau'),
    Prompt.create('fine art parody'),
    Prompt.create('flame painter'),
    Prompt.create('impressionism'),
    Prompt.create('ligne claire'),
    Prompt.create('nihonga'),
    Prompt.create('minimalism'),
    Prompt.create('realistic'),
    Prompt.create('photorealistic'),
    Prompt.create('sketch'),
    Prompt.create('surreal'),
    Prompt.create('unfinished')
  ],
  Techniques: [
    Prompt.create('backlighting'),
    Prompt.create('blending'),
    Prompt.create('bloom'),
    Prompt.create('bokeh'),
    Prompt.create('caustics'),
    Prompt.create('chiaroscuro'),
    Prompt.create('chromatic aberration'),
    Prompt.create('diffraction spikes'),
    Prompt.create('depth of field'),
    Prompt.create('dithering'),
    Prompt.create('drop shadow'),
    Prompt.create('emphasis lines'),
    Prompt.create('film grain'),
    Prompt.create('foreshortening'),
    Prompt.create('gradient'),
    Prompt.create('halftone'),
    Prompt.create('double exposure'),
    Prompt.create('lens flare'),
    Prompt.create('motion blur'),
    Prompt.create('motion lines'),
    Prompt.create('multiple monochrome'),
    Prompt.create('optical illusion'),
    Prompt.create('scanlines'),
    Prompt.create('silhouette'),
    Prompt.create('speed lines'),
    Prompt.create('vignetting')
  ],
  Flaws: [
    Prompt.create('Artifacts'),
    Prompt.create('gif artifacts'),
    Prompt.create('jpeg artifacts'),
    Prompt.create('aliasing'),
    Prompt.create('vhs artifacts'),
    Prompt.create('bad aspect ratio'),
    Prompt.create('blurry'),
    Prompt.create('censored'),
    Prompt.create('uncensored'),
    Prompt.create('duplicate'),
    Prompt.create('bad reflection'),
    Prompt.create('extra digits'),
    Prompt.create('typo'),
    Prompt.create('lossless-lossy'),
    Prompt.create('lossy-lossless'),
    Prompt.create('image macro'),
    Prompt.create('md5 mismatch'),
    Prompt.create('moire'),
    Prompt.create('poorly drawn'),
    Prompt.create('anatomical nonsense'),
    Prompt.create('bad anatomy'),
    Prompt.create('bad feet'),
    Prompt.create('bad hands'),
    Prompt.create('bad proportions'),
    Prompt.create('ranguage'),
    Prompt.create('reversed'),
    Prompt.create('rotated'),
    Prompt.create('solid color thumbnail'),
    Prompt.create('unmoving pattern'),
    Prompt.create('watermark'),
    Prompt.create('extraction')
  ]
};
