export class Prompt {
  public emphasis: number = 0;
  constructor(public value: string) {}
  toString(): string {
    if (this.emphasis > 0) {
      return '('.repeat(this.emphasis) + this.value + ')'.repeat(this.emphasis);
    }
    if (this.emphasis < 0) {
      return '['.repeat(-1 * this.emphasis) + this.value + ']'.repeat(-1 * this.emphasis);
    }
    return this.value;
  }
  static create(value: string): Prompt {
    return new Prompt(value);
  }
}

export const clamp = (value: number, min: number, max: number = Number.MAX_VALUE) =>
  Math.min(Math.max(value, min), max);

export const DEFAULT_COMPOSITION_PROMPTS: { [group: string]: Prompt[] } = {
  'View Angle': [
    { value: 'dutch angle', emphasis: 0 },
    { value: 'from above', emphasis: 0 },
    { value: 'from behind', emphasis: 0 },
    { value: 'from below', emphasis: 0 },
    { value: 'from side', emphasis: 0 },
    { value: 'sideways', emphasis: 0 },
    { value: 'straight-on', emphasis: 0 },
    { value: 'upside-down', emphasis: 0 }
  ],
  'Perspective / Depth': [
    { value: 'atmospheric perspective', emphasis: 0 },
    { value: 'fisheye', emphasis: 0 },
    { value: 'panorama', emphasis: 0 },
    { value: 'perspective', emphasis: 0 },
    { value: 'vanishing point', emphasis: 0 }
  ],
  Composition: [
    { value: 'afterimage', emphasis: 0 },
    { value: 'outside border', emphasis: 0 },
    { value: 'fading border', emphasis: 0 },
    { value: 'rounded corners', emphasis: 0 },
    { value: 'viewfinder', emphasis: 0 },
    { value: 'chart', emphasis: 0 },
    { value: 'bust chart', emphasis: 0 },
    { value: 'character chart', emphasis: 0 },
    { value: 'reference sheet', emphasis: 0 },
    { value: 'diagram', emphasis: 0 },
    { value: 'move chart', emphasis: 0 },
    { value: 'relationship graph', emphasis: 0 },
    { value: 'seating chart', emphasis: 0 },
    { value: 'stats', emphasis: 0 },
    { value: 'collage', emphasis: 0 },
    { value: 'column lineup', emphasis: 0 },
    { value: 'out of frame', emphasis: 0 },
    { value: 'fake scrollbar', emphasis: 0 },
    { value: 'head out of frame', emphasis: 0 },
    { value: 'out-of-frame censoring', emphasis: 0 },
    { value: 'outside border', emphasis: 0 },
    { value: 'from outside', emphasis: 0 },
    { value: 'glitch', emphasis: 0 },
    { value: 'isometric', emphasis: 0 },
    { value: 'letterboxed', emphasis: 0 },
    { value: 'lineup', emphasis: 0 },
    { value: 'mosaic art', emphasis: 0 },
    { value: 'photomosaic', emphasis: 0 },
    { value: 'negative space', emphasis: 0 },
    { value: 'omake', emphasis: 0 },
    { value: 'partially underwater shot', emphasis: 0 },
    { value: 'pov', emphasis: 0 },
    { value: 'social media composition', emphasis: 0 },
    { value: 'symmetry', emphasis: 0 },
    { value: 'polar opposites', emphasis: 0 },
    { value: 'rotational symmetry', emphasis: 0 },
    { value: 'trim marks', emphasis: 0 }
  ],
  'Subject matter': [
    { value: 'cityscape', emphasis: 0 },
    { value: 'everyone', emphasis: 0 },
    { value: 'absolutely everyone', emphasis: 0 },
    { value: 'landscape', emphasis: 0 },
    { value: 'nature', emphasis: 0 },
    { value: 'no humans', emphasis: 0 },
    { value: 'off-topic', emphasis: 0 },
    { value: 'scenery', emphasis: 0 },
    { value: 'still life', emphasis: 0 },
    { value: 'animal focus', emphasis: 0 },
    { value: 'armpit focus', emphasis: 0 },
    { value: 'ass focus', emphasis: 0 },
    { value: 'back focus', emphasis: 0 },
    { value: 'book focus', emphasis: 0 },
    { value: 'breast focus', emphasis: 0 },
    { value: 'cloud focus', emphasis: 0 },
    { value: 'eye focus', emphasis: 0 },
    { value: 'food focus', emphasis: 0 },
    { value: 'foot focus', emphasis: 0 },
    { value: 'hand focus', emphasis: 0 },
    { value: 'hip focus', emphasis: 0 },
    { value: 'male focus', emphasis: 0 },
    { value: 'navel focus', emphasis: 0 },
    { value: 'other focus', emphasis: 0 },
    { value: 'pectoral focus', emphasis: 0 },
    { value: 'solo focus', emphasis: 0 },
    { value: 'vehicle focus', emphasis: 0 },
    { value: 'text focus', emphasis: 0 },
    { value: 'thigh focus', emphasis: 0 },
    { value: 'weapon focus', emphasis: 0 },
    { value: 'vehicle focus', emphasis: 0 },
    { value: 'wind chime focus', emphasis: 0 }
  ],
  Framing: [
    { value: 'face', emphasis: 0 },
    { value: 'portrait', emphasis: 0 },
    { value: 'upper body', emphasis: 0 },
    { value: 'lower body', emphasis: 0 },
    { value: 'cowboy shot', emphasis: 0 },
    { value: 'feet out of frame', emphasis: 0 },
    { value: 'full body', emphasis: 0 },
    { value: 'wide shot', emphasis: 0 },
    { value: 'very wide shot', emphasis: 0 },
    { value: 'close-up', emphasis: 0 },
    { value: 'cut-in', emphasis: 0 },
    { value: 'split crop', emphasis: 0 },
    { value: 'cropped legs', emphasis: 0 },
    { value: 'cropped torso', emphasis: 0 },
    { value: 'cropped arms', emphasis: 0 },
    { value: 'cropped shoulders', emphasis: 0 },
    { value: 'cropped head', emphasis: 0 }
  ],
  Styles: [
    { value: 'abstract', emphasis: 0 },
    { value: 'art deco', emphasis: 0 },
    { value: 'art nouveau', emphasis: 0 },
    { value: 'fine art parody', emphasis: 0 },
    { value: 'flame painter', emphasis: 0 },
    { value: 'impressionism', emphasis: 0 },
    { value: 'ligne claire', emphasis: 0 },
    { value: 'nihonga', emphasis: 0 },
    { value: 'minimalism', emphasis: 0 },
    { value: 'realistic', emphasis: 0 },
    { value: 'photorealistic', emphasis: 0 },
    { value: 'sketch', emphasis: 0 },
    { value: 'surreal', emphasis: 0 },
    { value: 'unfinished', emphasis: 0 }
  ],
  Techniques: [
    { value: 'backlighting', emphasis: 0 },
    { value: 'blending', emphasis: 0 },
    { value: 'bloom', emphasis: 0 },
    { value: 'bokeh', emphasis: 0 },
    { value: 'caustics', emphasis: 0 },
    { value: 'chiaroscuro', emphasis: 0 },
    { value: 'chromatic aberration', emphasis: 0 },
    { value: 'diffraction spikes', emphasis: 0 },
    { value: 'depth of field', emphasis: 0 },
    { value: 'dithering', emphasis: 0 },
    { value: 'drop shadow', emphasis: 0 },
    { value: 'emphasis lines', emphasis: 0 },
    { value: 'film grain', emphasis: 0 },
    { value: 'foreshortening', emphasis: 0 },
    { value: 'gradient', emphasis: 0 },
    { value: 'halftone', emphasis: 0 },
    { value: 'double exposure', emphasis: 0 },
    { value: 'lens flare', emphasis: 0 },
    { value: 'motion blur', emphasis: 0 },
    { value: 'motion lines', emphasis: 0 },
    { value: 'multiple monochrome', emphasis: 0 },
    { value: 'optical illusion', emphasis: 0 },
    { value: 'scanlines', emphasis: 0 },
    { value: 'silhouette', emphasis: 0 },
    { value: 'speed lines', emphasis: 0 },
    { value: 'vignetting', emphasis: 0 }
  ],
  Flaws: [
    { value: 'Artifacts', emphasis: 0 },
    { value: 'gif artifacts', emphasis: 0 },
    { value: 'jpeg artifacts', emphasis: 0 },
    { value: 'aliasing', emphasis: 0 },
    { value: 'vhs artifacts', emphasis: 0 },
    { value: 'bad aspect ratio', emphasis: 0 },
    { value: 'blurry', emphasis: 0 },
    { value: 'censored', emphasis: 0 },
    { value: 'uncensored', emphasis: 0 },
    { value: 'duplicate', emphasis: 0 },
    { value: 'bad reflection', emphasis: 0 },
    { value: 'extra digits', emphasis: 0 },
    { value: 'typo', emphasis: 0 },
    { value: 'lossless-lossy', emphasis: 0 },
    { value: 'lossy-lossless', emphasis: 0 },
    { value: 'image macro', emphasis: 0 },
    { value: 'md5 mismatch', emphasis: 0 },
    { value: 'moire', emphasis: 0 },
    { value: 'poorly drawn', emphasis: 0 },
    { value: 'anatomical nonsense', emphasis: 0 },
    { value: 'bad anatomy', emphasis: 0 },
    { value: 'bad feet', emphasis: 0 },
    { value: 'bad hands', emphasis: 0 },
    { value: 'bad proportions', emphasis: 0 },
    { value: 'ranguage', emphasis: 0 },
    { value: 'reversed', emphasis: 0 },
    { value: 'rotated', emphasis: 0 },
    { value: 'solid color thumbnail', emphasis: 0 },
    { value: 'unmoving pattern', emphasis: 0 },
    { value: 'watermark', emphasis: 0 },
    { value: 'extraction', emphasis: 0 }
  ]
};
